; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
lib_deps = 
    # För DHT11
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

    # För MQTT
    arduino-libraries/ArduinoMqttClient @ ^0.1.8

    # För BLE
    arduino-libraries/ArduinoBLE @ ^1.3.7

   # För DS18B20
    milesburton/DallasTemperature @ ^3.9.1
    paulstoffregen/OneWire @ ^2.3.8
    bblanchon/ArduinoJson @ ^7.0.0

build_flags =
    -D WIFI_SSID=\"ssid\"
    -D WIFI_PASS=\"pass\"
