; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
#lib_deps =
#    robtillaart/DHTNEW
#lib_deps =
#    https://github.com/olewolf/DHT_nonblocking
lib_deps = 
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    arduino-libraries/ArduinoMqttClient @ ^0.1.8
    arduino-libraries/ArduinoBLE @ ^1.3.7
build_flags =
    -D WIFI_SSID=\"headingfornature\"
    -D WIFI_PASS=\"pass\"
